import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pål Smitt-Amundsen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-center items-center min-h-screen'>
        <section className='max-w-3xl'>
          <h1 className="font-bold text-2xl">Pål Smitt-Amundsen</h1>
          <p>Creative technologist / Business Developer / Conference Speaker</p>
          <p><a className="text-black underline" href="mailto:paal@paal.org">paal@paal.org</a></p>
        </section>
      </main>
    </>
  )
}
